//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Employee_App.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Info
    {
        public long id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<decimal> Income { get; set; }
        public string Cell_Number { get; set; }
        public string Email { get; set; }
    }
}
